### ISSUE TITLE
Releases at https://www.ecoinformatics.org/oboe/... are offline 

### ISSUE THREAD

**Issue by SArndt-TIB** [NCEAS/oboe#25]
Dear all,

your release namespace (e.g. https://www.ecoinformatics.org/oboe/oboe.1.2/oboe.owl) mentioned in your readme, has been down the last two days.

Just wanted to let you know (if not intentional). Thank's for fixing!

All the best

Susanne

**Comment by mbjones** [comment]
Thanks for the report, we'll check it out.

**Comment by mbjones** [comment]
@SArndt-TIB Taking a quick look, I noticed that you used an `https` address, rather than the published `http` address for our OBOE namespace. the official namespace is `http://ecoinformatics.org/oboe/oboe.1.2/oboe.owl` and that seems to be working fine for me. Is it possible your client is automatically converting http to https and trying to resolve it (as that does not work, at least for now). We should probably upgrade the namespace to https, but this was released at a time when some rdf tools did not reliably support https, and we haven't gone back and mapped the old namespace to a new https one.

**Comment by SArndt-TIB** [comment]
@mbjones That's exactly what happened in my browser, sorry I did not notice. We are using the http-adress in an OLS instance, though, where we perform a couple of tests for each ontology. I took a closer look: there was a time-out error, apparently caused by too many retries to connect to oboe. That happened for the first time, as far as I know - we did not have that problem before. Also, it does not seem to be happeing now. I guess I'll take it to our devs for now. Thanks a lot for your immediate reply - it's very appreciated!
